repository_type: pipeline
lint:
  files_unchanged:
    - docs/images/nf-core-viralgenie_logo_light.png
    - docs/images/nf-core-viralgenie_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/CONTRIBUTING.md
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/branch.yml
    - .github/workflows/linting.yml
    - assets/email_template.html
    - assets/email_template.txt
    - assets/sendmail_template.txt
  nextflow_config:
    - manifest.name
    - manifest.homePage
  multiqc_config:
    - report_section_order
    - report_comment
  files_exist:
    - conf/test.config
    - conf/test_full.config
template:
  name: viralgenie
  description: a bioinformatics best-practice analysis pipeline for reconstructing consensus genomes and to identify intra-host variants from metagenomic sequencing data or enriched based sequencing data like hybrid capture.
  author: Joon-Klaps
