repository_type: pipeline
lint:
  files_unchanged:
    - docs/images/nf-core-viralgenie_logo_light.png
    - docs/images/nf-core-viralgenie_logo_dark.png
    - docs/README.md
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/branch.yml
    - .github/workflows/linting.yml
    - .github/workflows/linting_comment.yml
    - assets/email_template.html
    - assets/email_template.txt
    - assets/sendmail_template.txt
    - pyproject.toml
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - config_defaults:
        - params.annotation_db
        - params.multiqc_comment_headers
        - params.custom_table_headers
  multiqc_config:
    - report_section_order
    - report_comment
  files_exist:
    - .github/CONTRIBUTING.md
    - CITATIONS.md
    - conf/test.config
    - conf/test_full.config
    - lib/Utils.groovy
    - lib/WorkflowMain.groovy
    - lib/NfcoreTemplate.groovy
    - lib/WorkflowViralgenie.groovy
    - assets/nf-core-viralgenie_logo_light.png
  actions_awsfulltest:
    - .github/workflows/awsfulltest.yml
    - .github/workflows/awstest.yml
template:
  name: viralgenie
  description: a bioinformatics best-practice analysis pipeline for reconstructing consensus genomes and to identify intra-host variants from metagenomic sequencing data or enriched based sequencing data like hybrid capture.
  author: Joon-Klaps
