repository_type: pipeline
template:
  author: Joon-Klaps
  description: a bioinformatics best-practice analysis pipeline for reconstructing
    consensus genomes and to identify intra-host variants from metagenomic sequencing
    data or enriched based sequencing data like hybrid capture.
  name: viralgenie
