repository_type: pipeline
lint:
  files_unchanged:
    - docs/images/nf-core-viralgenie_logo_light.png
    - docs/images/nf-core-viralgenie_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/ISSUE_TEMPLATE/config.yml
