bump_version: null
nf_core_version: 3.1.0
org_path: null
repository_type: pipeline
lint:
  files_unchanged:
    - docs/images/nf-core-viralgenie_logo_light.png
    - docs/images/nf-core-viralgenie_logo_dark.png
    - docs/README.md
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/branch.yml
    - .github/workflows/linting.yml
    - .github/workflows/linting_comment.yml
    - assets/email_template.html
    - assets/email_template.txt
    - assets/sendmail_template.txt
    - pyproject.toml
    - .gitignore
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - config_defaults:
        - params.multiqc_comment_headers
        - params.custom_table_headers
  multiqc_config: false
  files_exist:
    - .github/CONTRIBUTING.md
    - CITATIONS.md
    - assets/nf-core-viralgenie_logo_light.png
    - conf/test.config
    - conf/test_full.config
  actions_awsfulltest: false
  actions_ci: false
template:
  name: viralgenie
  description: a bioinformatics best-practice analysis pipeline for reconstructing consensus genomes and to identify intra-host variants from metagenomic sequencing data or enriched based sequencing data like hybrid capture.
  author: "Joon Klaps, Philippe Lemey, Liana Kafetzopoulou"
  is_nfcore: false
  org: Joon-Klaps
  skip_features:
    - igenomes
  force: false
  outdir: .
  version: 0.1.1dev
update: null
