site_name: Viralgenie
repo_name: Joon-Klaps/viralgenie
repo_url: https://github.com/Joon-Klaps/viralgenie
site_url: https://joon-klaps.github.io/viralgenie/

nav:
  - Home:
      - "Introduction": README.md
      - "Installation": installation.md
      - "Usage": usage.md
      - "Output": output.md
      - "Citations": CITATIONS.md
  - Workflow:
      - "Pipeline overview": workflow/overview.md
      - "Preprocessing": workflow/preprocessing.md
      - "Assembly polishing": workflow/assembly_polishing.md
      - "Variant analysis & Iterative refinement": workflow/iterative_refinement.md
  - Customisation:
      - "Databases": customisation/databases.md
      - "Configuration": customisation/configuration.md
  - Contributing: "CONTRIBUTING.md"

  # - Parameters:
  #     - parameters/validation.md
  #     - parameters/help_text.md
  #     - parameters/summary_log.md
  # - Samplesheets:
  #     - samplesheets/validate_sample_sheet.md
  #     - samplesheets/fromSamplesheet.md
  #     - samplesheets/examples.md
  # - Contributing:
  #     - contributing/setup.md

theme:
  name: material
  favicon: images/ViralGenie-nf-core-theme.png
  logo: images/ViralGenie-nf-core-theme.png
  palette:
    - media: "(prefers-color-scheme)"
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      # scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  font:
    text: "Ubuntu"
    code: "Ubuntu Mono"
  features:
    - announce.dismiss
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - header.autohide
    - navigation.footer
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.share
    - search.suggest
    - toc.follow
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - def_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
# plugins:
#   - search
#   - social:
#       cards: !ENV [CARDS, true]

extra:
  version:
    provider: mike
  analytics:
    provider: google
    property: G-DJ9PDTBEEC
  consent:
    title: Cookie Consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/LemeyLab
