name: "hostremoval_bowtie2_samtools"
description: Removal of host reads using bowtie2 and samtools given a reference
keywords:
  - bowtie2
  - samtools
  - contamination
  - filtered reads

modules:
  - bowtie2/build
  - bowtie2/align
  - samtools/index
  - samtools/stats
  - samtools/view

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - reads:
      type: file
      description: |
        List of input FastQ files of size 1 and 2 for single-end and paired-end data,
        respectively.
  - reference:
      type: file
      description: reference genome fasta file
  - index:
      type: file
      description: Bowtie2 genome index files
      pattern: "*.ebwt"

output:
  - stats:
      type: file
      description: File containing samtools stats output
      pattern: "*.{stats}"
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test' ]
  - reads:
      type: file
      description: Unaligned FastQ files
      pattern: "*.fastq.gz"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - mqc:
      type: file
      description: statistics and logs of samtools and bowtie2
