contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here for general nextflow pipeline discussions.
  - name: "Find me on the nf-core slack"
    url: https://nfcore.slack.com/team/U043Y6FQR6J
    about: Ask me anything about viralgenie on slack.
