contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #viralgenie channel"
    url: https://nfcore.slack.com/channels/viralgenie
    about: Discussion about the nf-core/viralgenie pipeline
