name: network_cluster
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::leidenalg=0.10.1
  - conda-forge::python-igraph=0.11.3
  - conda-forge::pandas=2.1.3
  - conda-forge::matplotlib=3.8.2
  - conda-forge::pycairo=1.25.1
