name: lowcov_to_reference
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::cython=3.0.10
  - conda-forge::biopython=1.83
  - pip:
      - git+https://github.com/althonos/pymuscle5
