name: nf-core CI
# This workflow runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on:
  push:
    branches:
      - dev
  pull_request_target:
  release:
    types: [published]
  workflow_dispatch:

env:
  NXF_ANSI_LOG: false
  NXF_SINGULARITY_CACHEDIR: ${{ github.workspace }}/.singularity
  NXF_SINGULARITY_LIBRARYDIR: ${{ github.workspace }}/.singularity

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request_target.number || github.ref }}"
  cancel-in-progress: true

jobs:
  test-variant-callers:
    name: "Run pipeline with test data (${{ matrix.NXF_VER }}) | (${{ matrix.profile }}) | (${{ matrix.VARIANT_CALLER }} - ${{ matrix.CONSENSUS_CALLER }})"
    # Only run on push if this is the nf-core dev branch (merged PRs)
    if: "${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'Joon-Klaps/viralgenie') }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER:
          - "24.04.2"
          - "latest-everything"
        VARIANT_CALLER:
          - "bcftools"
          - "ivar"
        CONSENSUS_CALLER:
          - "bcftools"
          - "ivar"
        profile:
          - "conda"
          - "docker"
          - "singularity"
        test_name:
          - "test"
        isMaster:
          - ${{ github.base_ref == 'master' }}
        # Exclude conda and singularity on dev
        exclude:
          - isMaster: false
            profile: "conda"
          - isMaster: false
            profile: "singularity"
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b #4

      - name: Free some space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Set up Apptainer
        if: matrix.profile == 'singularity'
        uses: eWaterCycle/setup-apptainer@main

      - name: Set up Singularity
        if: matrix.profile == 'singularity'
        run: |
          mkdir -p $NXF_SINGULARITY_CACHEDIR
          mkdir -p $NXF_SINGULARITY_LIBRARYDIR

      - name: Set up Miniconda
        if: matrix.profile == 'conda'
        uses: conda-incubator/setup-miniconda@a4260408e20b96e80095f42ff7f1a15b27dd94ca # v3
        with:
          miniconda-version: "latest"
          auto-update-conda: true
          conda-solver: libmamba
          channels: conda-forge,bioconda

      - name: Set up Conda
        if: matrix.profile == 'conda'
        run: |
          echo $(realpath $CONDA)/condabin >> $GITHUB_PATH
          echo $(realpath python) >> $GITHUB_PATH

      - name: Clean up Disk space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1

      - name: Run pipeline with small test data with variant caller ${{ matrix.VARIANT_CALLER }} and consensus caller ${{ matrix.CONSENSUS_CALLER }}
        env:
          VARIANT_CALLER: ${{ matrix.VARIANT_CALLER }}
          CONSENSUS_CALLER: ${{ matrix.CONSENSUS_CALLER }}
          profile: ${{ matrix.profile }}
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test,${profile} --variant_caller ${VARIANT_CALLER} --consensus_caller ${CONSENSUS_CALLER} --outdir ./results

  test-cluster-methods:
    name: "Run pipeline with test data (${{ matrix.NXF_VER }}) | (${{ matrix.profile }}) | (${{ matrix.CLUSTER_METHOD }})"
    # Only run on push if this is the nf-core dev branch (merged PRs)
    if: "${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'Joon-Klaps/viralgenie') }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER:
          - "24.04.2"
          - "latest-everything"
        CLUSTER_METHOD:
          - "vsearch"
          - "mmseqs-cluster"
          - "mmseqs-linclust"
          - "mash"
          - "vrhyme"
          - "cdhitest"
        profile:
          - "conda"
          - "docker"
          - "singularity"
        test_name:
          - "test"
        isMaster:
          - ${{ github.base_ref == 'master' }}
        # Exclude conda and singularity on dev
        exclude:
          - isMaster: false
            profile: "conda"
          - isMaster: false
            profile: "singularity"
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b #4

      - name: Free some space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Set up Apptainer
        if: matrix.profile == 'singularity'
        uses: eWaterCycle/setup-apptainer@main

      - name: Set up Singularity
        if: matrix.profile == 'singularity'
        run: |
          mkdir -p $NXF_SINGULARITY_CACHEDIR
          mkdir -p $NXF_SINGULARITY_LIBRARYDIR

      - name: Set up Miniconda
        if: matrix.profile == 'conda'
        uses: conda-incubator/setup-miniconda@a4260408e20b96e80095f42ff7f1a15b27dd94ca # v3
        with:
          miniconda-version: "latest"
          auto-update-conda: true
          conda-solver: libmamba
          channels: conda-forge,bioconda

      - name: Set up Conda
        if: matrix.profile == 'conda'
        run: |
          echo $(realpath $CONDA)/condabin >> $GITHUB_PATH
          echo $(realpath python) >> $GITHUB_PATH

      - name: Clean up Disk space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1

      - name: Run pipeline with small test data using ${{ matrix.CLUSTER_METHOD }}
        env:
          CLUSTER_METHOD: ${{ matrix.CLUSTER_METHOD }}
          profile: ${{ matrix.profile }}
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test,${profile} --cluster_method ${CLUSTER_METHOD} --skip_iterative_refinement --skip_variant_calling --outdir ./results

  test-others:
    name: "Run pipeline with various test profiles (${{ matrix.test_name }}) | (${{ matrix.NXF_VER }}) | (${{ matrix.profile }})"
    # Only run on push if this is the nf-core dev branch (merged PRs)
    if: "${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'Joon-Klaps/viralgenie') }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER:
          - "24.04.2"
          - "24.04.2"
          - "latest-everything"
        profile:
          - "conda"
          - "docker"
          - "singularity"
        test_name:
          - "test_full"
          - "test_nothing"
          - "test_fail_mapped"
          - "test_fail_db"
          - "test_umi"
        isMaster:
          - ${{ github.base_ref == 'master' }}
        # Exclude conda and singularity on dev
        exclude:
          - isMaster: false
            profile: "conda"
          - isMaster: false
            profile: "singularity"
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b #4

      - name: Free some space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Set up Apptainer
        if: matrix.profile == 'singularity'
        uses: eWaterCycle/setup-apptainer@main

      - name: Set up Singularity
        if: matrix.profile == 'singularity'
        run: |
          mkdir -p $NXF_SINGULARITY_CACHEDIR
          mkdir -p $NXF_SINGULARITY_LIBRARYDIR

      - name: Set up Miniconda
        if: matrix.profile == 'conda'
        uses: conda-incubator/setup-miniconda@a4260408e20b96e80095f42ff7f1a15b27dd94ca # v3
        with:
          miniconda-version: "latest"
          auto-update-conda: true
          conda-solver: libmamba
          channels: conda-forge,bioconda

      - name: Set up Conda
        if: matrix.profile == 'conda'
        run: |
          echo $(realpath $CONDA)/condabin >> $GITHUB_PATH
          echo $(realpath python) >> $GITHUB_PATH

      - name: Clean up Disk space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1

      - name: Run pipeline with small test data using ${{ matrix.test_name }} | ${{ matrix.profile }}
        env:
          test_name: ${{ matrix.test_name }}
          profile: ${{ matrix.profile }}
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile ${test_name},${profile} --outdir ./results
