name: nf-core CI
# This workflow runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on:
  push:
    branches:
      - dev
  pull_request:
  release:
    types: [published]

env:
  NXF_ANSI_LOG: false

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: Run pipeline with test data
    # Only run on push if this is the nf-core dev branch (merged PRs)
    if: "${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'nf-core/viralgenie') }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER:
          - "23.04.0"
          - "latest-everything"
        VARIANT_CALLER:
          - "bcftools"
          - "ivar"
        CONSENSUS_CALLER:
          - "bcftools"
          - "ivar"
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v4

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Run pipeline with small test data with variant caller ${{ matrix.VARIANT_CALLER }} and consensus caller ${{ matrix.CONSENSUS_CALLER }}
        env:
          VARIANT_CALLER: ${{ matrix.VARIANT_CALLER }}
          CONSENSUS_CALLER: ${{ matrix.CONSENSUS_CALLER }}
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test,docker --variant_caller ${VARIANT_CALLER} --consensus_caller ${CONSENSUS_CALLER} --outdir ./results --max_cpus 2 --max_memory 4GB

  test-full:
    name: Run complete pipeline with more test data
    # Only run on push if this is the nf-core dev branch (merged PRs)
    if: "${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'nf-core/viralgenie') }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER:
          - "23.04.0"
          - "latest-everything"
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v4

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Run complete pipeline with more test data
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test_full,docker --outdir ./results --max_cpus 4 --max_memory 15GB

  test-umi:
    name: Run pipeline with test umi data
    # Only run on push if this is the nf-core dev branch (merged PRs)
    if: "${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'nf-core/viralgenie') }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER:
          - "23.04.0"
          - "latest-everything"
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v4

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Run pipeline with umi test data
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test_umi,docker --outdir ./results --max_cpus 2 --max_memory 4GB

  test-nothing:
    name: Run pipeline and skip everything
    # Only run on push if this is the nf-core dev branch (merged PRs)
    if: "${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'nf-core/viralgenie') }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER:
          - "23.04.0"
          - "latest-everything"
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v4

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Run pipeline but skip all steps
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test_nothing,docker --outdir ./results --max_cpus 2 --max_memory 4GB

  test-fail-mapped:
    name: Run pipeline with test bad mapping constrained reference
    # Only run on push if this is the nf-core dev branch (merged PRs)
    if: "${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'nf-core/viralgenie') }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER:
          - "23.04.0"
          - "latest-everything"
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v4

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Run pipeline with umi test data
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test_fail_mapped,docker --outdir ./results --max_cpus 2 --max_memory 4GB

  test-fail-db:
    name: Run pipeline with test bad database for identifying potential references
    # Only run on push if this is the nf-core dev branch (merged PRs)
    if: "${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'nf-core/viralgenie') }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER:
          - "23.04.0"
          - "latest-everything"
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v4

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Run pipeline with test data of a bad reference database
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test_fail_db,docker --outdir ./results --max_cpus 2 --max_memory 4GB

  test-cluster-methods:
    name: Run pipeline with minimal test data and different cluster methods
    # Only run on push if this is the nf-core dev branch (merged PRs)
    if: "${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'nf-core/viralgenie') }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER:
          - "latest-everything"
        CLUSTER_METHOD:
          - "vsearch"
          - "mmseqs-cluster"
          - "mmseqs-linclust"
          - "mash"
          - "vrhyme"
          - "cdhitest"
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v4

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Run pipeline with test data and cluster using ${{ matrix.CLUSTER_METHOD }}
        env:
          CLUSTER_METHOD: ${{ matrix.CLUSTER_METHOD }}
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test,docker --cluster_method ${CLUSTER_METHOD} --skip_iterative_refinement --skip_variant_calling --outdir ./results --max_cpus 4 --max_memory 15GB
